## 配置信息：后必须有一个空格
## Site
title: Deep Thinking         ## 网站标题
subtitle:  ## 简介
description: 随心 随笔          ## 描述
author: Charlotte                ## 网站作者
language: zh-Hans               ## 网站语言
email: yhw1813@gmail.com
timezone: Asia/Hong_Kong        #时区

#主题
theme: maupassant-hexo-master
#多说评论
duoshuo_shortname: charlotteblog
#头像
avatar: /uploads/avatar.jpg
## Deployment
### Docs: http://hexo.io/docs/deployment.html
